#!/usr/bin/env python3
"""
Numerology Milestones: let the marketplace celebrate its own pulse.

Counts merged PRs touching `main` and emits a milestone markdown
whenever the count crosses one of the sacred multiples (7, 49, 369).
State is persisted in `signals/cycles.json` so each crossing fires
exactly once; the workflow commits the milestone file and updated
state back to main with `[skip ci]`.

Layers:
  - Every 7 PRs → `milestones/7-{n}.md` (small note)
  - Every 49 PRs → `milestones/49-{n}.md` (medium reflection)
  - Every 369 PRs → `milestones/369-{n}.md` (large checkpoint)

The milestones reference the last 7/49/369 commits respectively, so
they are self-documenting time capsules with no human effort. The
script is idempotent: re-running with the same git state and same
state file is a no-op.
"""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SIGNALS = ROOT / "signals"
STATE = SIGNALS / "cycles.json"
MILESTONES = ROOT / "milestones"

TIERS = (
    ("7", 7),
    ("49", 49),
    ("369", 369),
)


def _git(*args: str) -> str:
    try:
        return subprocess.check_output(["git", "-C", str(ROOT), *args], text=True).strip()
    except subprocess.CalledProcessError:
        return ""


def _count_merges_on_main() -> int:
    raw = _git("log", "--first-parent", "--merges", "main", "--pretty=format:%H")
    if not raw:
        return 0
    return len(raw.splitlines())


def _recent_log(n: int) -> list[str]:
    raw = _git(
        "log",
        f"-n{n}",
        "--first-parent",
        "--merges",
        "main",
        "--pretty=format:- `%h` %ad: %s",
        "--date=short",
    )
    return raw.splitlines() if raw else []


def _load_state() -> dict:
    """
    Load `signals/cycles.json` and return it as a dict. Guards against
    a malformed file (non-object root, non-int counters) so a corrupt
    state file can never crash the workflow; on any structural issue
    the state is treated as empty and rebuilt from the git history.
    """
    if not STATE.is_file():
        return {}
    try:
        raw = json.loads(STATE.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}
    if not isinstance(raw, dict):
        return {}
    cleaned: dict = {}
    for label, _ in TIERS:
        value = raw.get(label, 0)
        cleaned[label] = value if isinstance(value, int) and value >= 0 else 0
    last_total = raw.get("last_total", 0)
    if isinstance(last_total, int) and last_total >= 0:
        cleaned["last_total"] = last_total
    if isinstance(raw.get("last_run"), str):
        cleaned["last_run"] = raw["last_run"]
    return cleaned


def _save_state(state: dict) -> None:
    SIGNALS.mkdir(parents=True, exist_ok=True)
    STATE.write_text(json.dumps(state, indent=2) + "\n", encoding="utf-8")


def _emit(tier_label: str, ordinal: int, total_merges: int, recent: list[str]) -> Path:
    MILESTONES.mkdir(parents=True, exist_ok=True)
    target = MILESTONES / f"{tier_label}-{ordinal}.md"
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    head = _git("rev-parse", "--short", "HEAD") or "unknown"

    body: list[str] = []
    body.append(f"# Milestone {tier_label}: #{ordinal}")
    body.append("")
    body.append(f"_Marketplace crossed {ordinal * int(tier_label)} merged PRs at {now}, HEAD `{head}`._")
    body.append(f"_Total merges on main at this point: {total_merges}._")
    body.append("")
    body.append(f"## Last {tier_label} merges leading here")
    body.append("")
    if recent:
        body.extend(recent)
    else:
        body.append("- _(no merge history available)_")
    body.append("")
    body.append("---")
    body.append("_Auto-generated by `scripts/milestones.py`. Do not hand-edit._")
    body.append("")
    target.write_text("\n".join(body), encoding="utf-8")
    return target


def main() -> int:
    total = _count_merges_on_main()
    state = _load_state()
    fired: list[str] = []

    for label, modulus in TIERS:
        already = state.get(label, 0)
        target_ordinal = total // modulus
        while already < target_ordinal:
            already += 1
            recent = _recent_log(modulus)
            path = _emit(label, already, total, recent)
            fired.append(str(path.relative_to(ROOT)))
        state[label] = already

    # Only persist state when at least one milestone fired. Otherwise
    # the file would change (last_run timestamp) on every workflow run
    # and pollute the git history with no-op commits. Idempotency is
    # the contract: same merge count + same state -> no writes.
    if fired:
        state["last_total"] = total
        state["last_run"] = datetime.now(timezone.utc).isoformat()
        _save_state(state)
        print("Milestones: fired " + ", ".join(fired))
    else:
        print(f"Milestones: nothing to fire (total merges = {total})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
